services:
  web:
    build: .
    container_name: desafio-api
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,web
      DB_NAME: desafio_aiqfome
      DB_USER: Gandalf
      DB_PASSWORD: Mellon
      DB_HOST: db
      DB_PORT: 5432
      ES_HOST: http://search:9200
      ES_PRODUCTS_INDEX: products
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: postgres:16
    container_name: desafio-postgres
    environment:
      POSTGRES_DB: desafio_aiqfome
      POSTGRES_USER: Gandalf
      POSTGRES_PASSWORD: Mellon
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Gandalf -d desafio_aiqfome"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: desafio-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres-data:
  elasticsearch-data:
