services:
  db:
    image: postgres:16
    container_name: desafio-postgres
    environment:
      POSTGRES_DB: desafio_aiqfome
      POSTGRES_USER: Gandalf
      POSTGRES_PASSWORD: Mellon
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
